### ISSUE TITLE
gem is not published on rubygems

### ISSUE THREAD

**Issue by ocha** [Storj/ruby-libstorj#5]
can storj team publish this gem on rubygems? It would be much easier to get dev start using it. Also, it would be awful if someone publishes malicious gem under this name and all users instal it since readme directs user to use `gem install ruby-libstorj`

**Comment by bryanchriswhite** [comment]
@ocha the gem isn't quite ready for release yet. The basic functionality required is mostly implemented (see issue #4) but the test suite still leaves a lot to be desired; the most glaring example of this is the current severe lack of error handling.

Point taken regarding the readme; I'll change it for now. We've not completely settled on the naming yet for the new binding libs so the gem name may change between now and when it gets initially published.
